#!/bin/bash
#SBATCH --job-name=flye_leon
#SBATCH --output=result.txt
#SBATCH --ntasks=1
#SBATCH --time=148:00:00
#SBATCH --mem-per-cpu=100
#SBATCH --cpus-per-task=100
#SBATCH --nodelist=heracpu01.nlzoh.si
#SBATCH --output=test.log


#export PATH=$PATH:/home/nlzoh.si/leomar1/miniconda3/bin
cd /home/storage/finished_projects/Leon/flye-test/
outdir=/home/storage/finished_projects/Leon/flye-test/


#!/bin/bash
echo ''
echo 'RUNNING FLYE'
echo ''


source /home/nlzoh.si/leomar1/.bashrc
source activate py27

for file in *.fastq.gz;  do
  while [ "$(jobs -p | wc -l)" -ge "$SLURM_NTASKS" ]; do
        sleep 30
  done
  filename=$(basename "$file")
	srun flye --nano-corr $file -t 48 -o ./"${filename}_output" 
done


mkdir assembly

for f in */*.fasta; do 
	cp $f ./${f%/assembly.fasta}.fasta;
	mv *.fasta assembly;
done
