#!/bin/bash

#As an example, your sequences appear as follows:
sample1_R1.fastq.gz sample1_R2.fastq.gz sample1_ont.fastq.gz 
sample2_R1.fastq.gz sample2_R2.fastq.gz sample2_ont.fastq.gz 
sample3_R1.fastq.gz sample3_R2.fastq.gz sample3_ont.fastq.gz

#nanofilt for filtering long read data

#!/bin/bash

for f in *R1*.fastq.gz*; do

    unicycler -1 $f -2 ${f/R1/R2} -l ${f/R1/ont} --verbosity 2 --min_component_size 500 --min_dead_end_size 500 --threads 8 -o ${f/_R1*/_hybrid_assembly} ;
done
